spring:
  thymeleaf:
    encoding: utf-8
    mode: HTML
    cache: false
  profiles:
    active: prod
server:
  port: 10993


#  ssl:
#    key-password: dAHXD4eC
#    protocol: TLS
#    key-store: classpath:6065309_www.jcohy.com.pfx
#    key-alias: tomcat
#    key-store-type: PKCS12
---

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/survey?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: jcohy1203
  config:
    activate:
      on-profile: dev

---

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://118.24.104.160:3306/survey?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 1405@xuanwu123A
  config:
    activate:
      on-profile: prod
