spring:
  thymeleaf:
    encoding: utf-8
    mode: HTML
    cache: false
  profiles:
    active: prod

  mail:
    port: 465
    username: jia_chao1203@126.com
    password: LLJHDLFIWNDXQIAQ
    host: smtp.126.com
    test-connection: true
    properties:
      mail:
        smtp:
          auth: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false
          starttls:
            enable: true
            required: true
server:
  port: 10993



#  ssl:
#    key-password: dAHXD4eC
#    protocol: TLS
#    key-store: classpath:6065309_www.jcohy.com.pfx
#    key-alias: tomcat
#    key-store-type: PKCS12
---

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/survey?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: jcohy1203
  config:
    activate:
      on-profile: dev
host: http://localhost:10993/index
---

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/survey?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 1405@xuanwu123A
  config:
    activate:
      on-profile: prod
host: http://124.222.90.247:10993/index